play with detect

diff --git a/bin/detect b/bin/detect
--- a/bin/detect
+++ b/bin/detect
@@ -10,12 +10,25 @@
 # http://docs.cloudfoundry.com/docs/using/deploying-apps/custom-buildpacks.html
 # -----------------------------------------------------------------------------
 
-RC_OK=0
-RC_FAIL=1
+BUILD_DIR="$1"
+
+# Fail Fast
+set -o errexit
+set -o pipefail
+
 
 function main {
+
+    if [ -d "$BUILD_DIR" ] 
+    then
+	    cd "$BUILD_DIR"
+	else
+		echo "Build dir does not exist. Failing"
+		exit 1
+	fi
+
     echo "BuildpackName"
-    exit $RC_OK
+    exit 0
 }
 
 main
